name: harmofl
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2021.10.26=h06a4308_2
  - cairo=1.16.0=hf32fb01_1
  - certifi=2021.10.8=py37h06a4308_0
  - ffmpeg=4.0=hcdf2ecd_0
  - fontconfig=2.13.1=h6c09931_0
  - freeglut=3.0.0=hf484d3e_5
  - freetype=2.11.0=h70c0345_0
  - glib=2.69.1=h5202010_0
  - graphite2=1.3.14=h23475e2_0
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hba1933b_1
  - icu=58.2=he6710b0_3
  - intel-openmp=2021.4.0=h06a4308_3561
  - jasper=2.0.14=hd8c5072_2
  - jpeg=9d=h7f8727e_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglu=9.0.0=hf484d3e_1
  - libopencv=3.4.2=hb342d67_1
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.2.0=h85742a9_0
  - libuuid=1.0.3=h7f8727e_2
  - libvpx=1.7.0=h439df22_0
  - libwebp-base=1.2.0=h27cfd23_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hb55368b_3
  - lz4-c=1.9.3=h295c915_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.1=py37hd3c417c_0
  - mkl_random=1.2.2=py37h51133e4_0
  - ncurses=6.2=he6710b0_1
  - numpy-base=1.21.2=py37h79a1101_0
  - opencv=3.4.2=py37h6fd60c2_1
  - openssl=1.1.1l=h7f8727e_0
  - pcre=8.45=h295c915_0
  - pip=20.2.4=py37h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - py-opencv=3.4.2=py37hb342d67_1
  - python=3.7.9=h7579374_0
  - readline=8.0=h7b6447c_0
  - setuptools=50.3.1=py37h06a4308_1
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.10=hbc83047_0
  - wheel=0.35.1=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - cython==0.29.24
    - dataclasses==0.6
    - future==0.18.2
    - numpy==1.19.4
    - pillow==8.0.1
    - simpleitk==1.2.4
    - torch==1.7.0
    - torchvision==0.8.1
    - typing-extensions==3.7.4.3


